// Generated by https://quicktype.io

import { MovieResult } from "./popularMovies";

export interface SearchResult {
  page: number;
  results: MovieResult[];
  total_pages: number;
  total_results: number;
}

export interface SearchQuery {
  query: string;
  page?: string;
}
